name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v1
              with:
                  python-version: 3.9
            - name: Setup
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  mkdir out
            - name: Build
              run: |
                python circuit_heatmap.py
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./out
